#!/bin/sh
set -e
alias print="printf \"\033[32m%s\n\033[0m\""
alias print_error="printf \"\033[31m%s\n\033[0m\""
api="https://api.mullvad.net/app/v1"
conf_dir=/var/lib/mlvd

is_connected() {
	ip link show mlvd > /dev/null 2>&1
	return
}
check_root() {
	if [ "$(id -u)" -ne 0 ]; then
		echo "This script must be run as root"
		exit 1
	fi
}
disconnect() {
	print "Disconnecting..."
	wg-quick down mlvd
}
get_active_relays() {
	curl -s "$api/relays" | jq ".wireguard.relays[] | select(.active == true)"
}
# TODO Cache relay list
list_relays() {
	get_active_relays | jq -r '.hostname + " (" + .provider + ")"'
}
connect() {
	print "Finding best server..."
	# TODO Add randomness to server selection like the official client does
	sel="$(get_active_relays | jq "select(.hostname | startswith(\"$1\" | ascii_downcase))" | jq -e -s 'sort_by(.weight)[-1]')"
	[ $? -eq 0 ] || { print_error "Couldn't find server hostname starting with \"$1\""; exit 1; }

	gateway="$(echo "$sel" | jq -r '.ipv4_addr_in')"
	hostname="$(echo "$sel" | jq -r '.hostname')"
	provider="$(echo "$sel" | jq -r '.provider')"
	server_pubkey="$(echo "$sel" | jq -r '.public_key')"

	print "Connecting to $hostname ($gateway, $provider)"
	sed -e "s|SERVER_PUBKEY|$server_pubkey|" -e "s|SERVER_IP|$gateway|" $conf_dir/template.conf > /etc/wireguard/mlvd.conf

	if is_connected; then
		wg-quick strip mlvd | wg setconf mlvd /dev/stdin
		wg set mlvd fwmark 0xca6c
	else
		wg-quick up mlvd
	fi && print "Connected successfully!"
}
help() { cat << EOF
Usage: mlvd [ c(onnect) | d(isconnect) | l(ist) ]

connect:
    # a server in germany
    mlvd c de
    # a server in frankfurt
    mlvd c de-fra
    # a specific server
    mlvd c de-fra-wg-402
disconnect:
    mlvd d
list active servers:
    mlvd l 

mlvd's files are in $conf_dir, edit template.conf to change WireGuard options

HOW TO SETUP: Download a WireGuard config file from your account panel
(https://mullvad.net/en/account/#/wireguard-config/) and copy
its "PrivateKey" and "Address" values into $conf_dir/template.conf
EOF
	exit
}

case $1 in
	c|connect) check_root; shift; connect "$@" ;;
	d|disconnect) check_root; disconnect ;;
	l|list) list_relays ;;
	*) help ;;
esac
